services:
  - type: web
    name: mlb-betting-ai
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: THESPORTSDB_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
